name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Set up SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Test JWT_PUBLIC_JWK systemd injection
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          JWT_PUBLIC_JWK: ${{ secrets.JWT_PUBLIC_JWK }}

        run: |
          set -e

          echo "Encoding JWT JSON..."

          JWT_B64=$(echo "$JWT_PUBLIC_JWK" | base64 -w 0)

          echo "Connecting to EC2..."

          ssh -o StrictHostKeyChecking=no \
            $EC2_USER@$EC2_HOST \
            "export JWT_B64='$JWT_B64' && \
             export EC2_USER='$EC2_USER' && \
             bash -s" << 'ENDSSH'

          set -e

          APP_DIR=/home/$EC2_USER/project-task-service

          echo "================ CLONE OR PULL REPOSITORY ================"

          if [ ! -d "$APP_DIR" ]; then
            git clone https://github.com/YOUR_GITHUB_USERNAME/YOUR_REPOSITORY.git $APP_DIR
          else
            cd $APP_DIR
            git pull origin main
          fi

          echo "Connected Successfully"

          JWT_PUBLIC_JWK=$(echo "$JWT_B64" | base64 -d)

          echo "================ DECODED JWT ================"
          echo "$JWT_PUBLIC_JWK"

          sudo tee /etc/systemd/system/test-jwt.service > /dev/null << EOF
          [Unit]
          Description=Test JWT Environment

          [Service]
          Type=oneshot
          Environment='JWT_PUBLIC_JWK=$JWT_PUBLIC_JWK'
          ExecStart=/bin/bash -c 'echo "JWT VALUE => \$JWT_PUBLIC_JWK"'

          [Install]
          WantedBy=multi-user.target
          EOF

          echo "================ SERVICE FILE ================"
          sudo cat /etc/systemd/system/test-jwt.service

          echo "================ RELOAD SYSTEMD ================"
          sudo systemctl daemon-reload

          echo "================ START SERVICE ================="
          sudo systemctl start test-jwt.service

          echo "================ SERVICE STATUS ================="
          sudo systemctl status test-jwt.service --no-pager || true

          echo "================ LOG OUTPUT =================="
          sudo journalctl -u test-jwt.service --no-pager

          ENDSSH
